data<-read.csv(unz("exdata-data-household_power_consumption.zip", "household_power_consumption.txt"), header=TRUE, sep=";", na.strings="?")
data$Date<-as.Date(data$Date, "%d/%m/%Y")
data$DateTime<-paste(data$Date, data$Time)
data$DateTime<-strptime(data$DateTime, "%Y-%m-%d %H:%M:%S")
sub<-subset(data, Date=="2007-02-01"|Date=="2007-02-02")
png("plot3.png")
with(sub, plot(DateTime,Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering"))
lines(sub$DateTime, sub$Sub_metering_2, type="l", col="red")
lines(sub$DateTime, sub$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c("Sub-metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=c(1,1))
dev.off()
